image: docker:latest

stages:
  - build-docker

build_docker:gitlab:
  image: docker:latest
  stage: build-docker
  tags:
    - docker
  only:
    - master
    - dev-master
    - dev-docker
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - |
      if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
        docker tag "$IMAGE_TAG" "${CI_REGISTRY_IMAGE}:latest"
        docker push "${CI_REGISTRY_IMAGE}:latest"
      fi

build_docker:dockerhub:
  image: docker:latest
  stage: build-docker
  tags:
    - docker
  only:
    - master
    - dev-master
    - dev-docker
  variables:
    IMAGE_TAG: samibourouis/balena-cli:latest
  before_script:
    - docker info
    - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

# Build docker
.build_docker:
  image: docker:latest
  stage: build-docker
  before_script:
    - docker info
    - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

build_docker:dockerhub:armhf:
  extends: .build_docker
  tags:
    - armv7
    - shell
  only:
    - master
    - dev-master
    - dev-docker
  variables:
    IMAGE_TAG: samibourouis/balena-cli:armhf
